apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: vault-init-test
  name: vault-init-test
  namespace: security
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vault-init-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault-init-test
    spec:
      containers:
      - image: melphos/vault-init-test:1.7-dbg
        imagePullPolicy: Always
        name: vault-init-test
      serviceAccount: vault
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
